- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with AWS"
    DURATION: "120HRS"
    TRAINER: "Sivakumar reddy"
  tasks:
    - name: print the information again
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}} with AWS, duration is {{DURATION}}, Trainer:{{TRAINER}}"

    - name: print the information again
      vars: # task level variables 
        COURSE: "Ansible"
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}} with AWS, duration is {{DURATION}}, Trainer:{{TRAINER}}"

     - name: print the information again and again
       ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}} with AWS, duration is {{DURATION}}, Trainer:{{TRAINER}}"

